/*
 * generated by Xtext
 */
package at.ac.tuwien.big.views.view;

import java.util.Properties;

import org.eclipse.xtext.Constants;

import com.google.inject.Binder;
import com.google.inject.name.Names;

/**
 * Manual modifications go to {at.ac.tuwien.big.views.view.ViewRuntimeModule}
 */
@SuppressWarnings("all")
public abstract class AbstractViewRuntimeModule extends org.eclipse.xtext.common.types.DefaultCommonTypesRuntimeModule {

}
