/**
 *
 * $Id$
 */
package views.validation;

import org.eclipse.emf.common.util.EList;

import views.Association;
import views.Property;

/**
 * A sample validator interface for {@link views.Class}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassValidator {
	boolean validate();

	boolean validateSuperclass(views.Class value);
	boolean validateSubclass(EList<views.Class> value);
	boolean validateProperties(EList<Property> value);
	boolean validateIsId(Property value);
	boolean validateAssociations(EList<Association> value);
	boolean validateAssociationsNavigable(EList<Association> value);
}
