/**
 *
 * $Id$
 */
package views.validation;

import views.Condition;
import views.Operator;

/**
 * A sample validator interface for {@link views.CompositeCondition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CompositeConditionValidator {
	boolean validate();

	boolean validateOperatorType(Operator value);
	boolean validateCond1(Condition value);
	boolean validateCond2(Condition value);
}
