/**
 *
 * $Id$
 */
package views.validation;

import org.eclipse.emf.common.util.EList;

import views.Association;
import views.DataType;
import views.Enumeration;

/**
 * A sample validator interface for {@link views.DomainModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DomainModelValidator {
	boolean validate();

	boolean validateClasses(EList<views.Class> value);
	boolean validateDataTypes(EList<DataType> value);
	boolean validateEnumerations(EList<Enumeration> value);
	boolean validateAssociations(EList<Association> value);
}
