/**
 *
 * $Id$
 */
package views.validation;

import views.ClassOperationView;

/**
 * A sample validator interface for {@link views.Link}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LinkValidator {
	boolean validate();

	boolean validateInstance(views.Class value);
	boolean validateView(ClassOperationView value);
}
