/**
 *
 * $Id$
 */
package views.validation;

import views.DomainModel;
import views.ViewModel;

/**
 * A sample validator interface for {@link views.Model}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelValidator {
	boolean validate();

	boolean validateDomainModel(DomainModel value);
	boolean validateViewModel(ViewModel value);
}
