/**
 *
 * $Id$
 */
package views.validation;

import org.eclipse.emf.common.util.EList;

import views.View;

/**
 * A sample validator interface for {@link views.ViewGroup}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ViewGroupValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateViews(EList<View> value);
	boolean validateStartView(View value);
}
