/**
 *
 * $Id$
 */
package views.validation;

import views.Layout;

/**
 * A sample validator interface for {@link views.View}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ViewValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateHeader(String value);
	boolean validateDescription(String value);
	boolean validateLayout(Layout value);
}
