/**
 *
 * $Id$
 */
package views.validation;

import org.eclipse.emf.common.util.EList;

import views.ViewGroup;

/**
 * A sample validator interface for {@link views.ViewModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ViewModelValidator {
	boolean validate();

	boolean validateViewGroups(EList<ViewGroup> value);
	boolean validateWelcomeViewGroup(ViewGroup value);
}
