<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="views" nsURI="http://www.example.org/views" nsPrefix="views">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superclass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subclass" ordered="false"
        upperBound="-1" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" ordered="false"
        upperBound="-1" eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//Property"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" ordered="false"
        upperBound="-1" eType="#//EnumLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="begin" lowerBound="1" eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" ordered="false"
        upperBound="-1" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" ordered="false"
        upperBound="-1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumerations" ordered="false"
        upperBound="-1" eType="#//Enumeration"/>
  </eClassifiers>
</ecore:EPackage>
